#include<stdio.h>
int main(){
// int s1,s2,s3,s4,s5,sum;
// float presentage;
// printf("enter the value of hindi=");
// scanf("%d",&s1);
// printf("enter the value of english=");
// scanf("%d",&s2);
// printf("enter the value of math=");
// scanf("%d",&s3);
// printf("enter the value of physics=");
// scanf("%d",&s4);
// printf("enter the value of chemistry=");
// scanf("%d",&s5);
// sum=s1+s2+s3+s4+s5;
// presentage=(s1+s2+s3+s4+s5)/5;
// printf("sum of 5 subjet=%d\n",sum);
// printf("presentage of 5 subjet=%f90",presentage);
// new code
// int a,b,sum,sub,mult,div,modulus;
// printf("enter the value of=");
// scanf("%d",&a);
// printf("enter the value of=");
// scanf("%d",&b);
// sum=a+b;
// sub=a-b;
// mult=a*b;
// div=a/b;
// modulus=a%b;
// printf("%d\n",sum);
// printf("%d\n",sub);
// printf("%d\n",mult);
// printf("%d\n",div);
// printf("%d",modulus);
// int a,b,ram,shyam,mohan,s1,s2,s3;
// printf("enter the value of=");
// scanf("%d",&a);
// printf("enter the value of=");
// scanf("%d",&b);
// ram=(a==b);
// shyam=(a!=b);
// mohan=(a>b);
// s1=(a<b);
// s2=(a>=b);
// s3=(a<=b);
// printf("%d\n",ram);
// printf("%d\n",shyam);
// printf("%d\n",mohan);
// printf("%d\n",ram);
// printf("%d\n",s1);
// printf("%d\n",s2);
// printf("%d\n",s3);
// int a,b,s1,s2,s3;
// printf("enter the value of=");
// scanf("%d",&a);
// printf("enter the value of=");
// scanf("%d",&b);
// s1=(a>b)&&(b<a);
// s2=(a>b)||(b<a);
// s3=!(a==b);
// printf("\n%d",s1);
// printf("\n%d",s2);
// printf("\n%d",s3);
// Assignment operators
// int a,b,s1,s2,s3,s4,s5,s6;
//  printf("enter the value of=");
//  scanf("%d",&a);
//   printf("enter the value of=");
//   scanf("%d",&b);
//  s1=(a=b);
// s2=(a+=b);
// s3=(a-=b);
// s4=(a*=b);
// s5=(a/=b);
// s6=(a%=b);
//  printf("\n%d",s1);
// printf("\n%d",s2);
// printf("\n%d",s3);
// printf("\n%d",s4);
// printf("\n%d",s5);
// printf("%d",s6);
 int a,b,vishalpatel;
 printf("enter the value of=");
 scanf("%d",&a);
 printf("enter the value of=");
 scanf("%d",&b);
  vishalpatel=(a>b)?a:b;
 printf("big number of value=%d",vishalpatel);
return 0;
}